services:
  - type: web
    name: sharebin
    plan: free
    numInstances: 1
    env: rust
    repo: https://github.com/timshel/sharebin.git
    buildCommand: cargo build --release
    startCommand: ./target/release/sharebin --editable --highlightsyntax
